
STAKE_ON_VALIDATOR = "5G3wMP3g3d775hauwmAZioYFVZYnvw6eY46wkFy8hEWD5KP3" #Replace with the hotkey of the validator you want to stake with (copy from https://taostats.io/validators )

WALLET_PW_FILE = '/home/user/.wallet_password.txt' #Replace with full location of a file containing the password for your wallet
WALLET_NAME = 'bagbot' #The name of the wallet created in btcli

MAX_TAO_PER_BUY = 0.02 #May increase as desired, I wouldnt reduce it
MAX_TAO_PER_SELL = 0.02 #May increase as desired, I wouldnt reduce it
MAX_SLIPPAGE_PERCENT_PER_BUY = 0.2 #If over this slippage %, buy trades won't execute.

# buy_lower is the lowest price that the bot will allocate your max_alpha amount to.  Will only purchase this low if you hold near the max_alpha amount.
# buy_upper is the highest price that the bot will allocate your max_alpha amount to.  Will only purchase this high if you hold no alpha in the subnet yet.
# sell_lower is the lowest price that the bot will sell your alpha.  Will only sell this low if you hold near the max_alpha amount.
# sell_upper is the highest price that the bot will sell your alpha.  Will only sell this high if you hold near almost no alpha in the subnet.
# max_alpha is the maximum amount of alpha to buy in the subnet, the bot will not purchase more.
SUBNET_SETTINGS = {
# Subnet 23 settings:
23: {'buy_lower': 0.000011,
     'buy_upper': 0.000015,
     'sell_lower': 0.0019,
     'sell_upper': 0.003,
     'max_alpha': 10000},
}


# COPY EVERYTHING ABOVE THIS LINE TO A NEW FILE NAMED: bagbot_settings_overrides.py IN THIS SAME DIRECTORY AND ADJUST AS NEEDED. DO NOT EDIT THIS FILE

try:
    from bagbot_settings_overrides import *
except:
    pass

